[ vk-mobile-nav ] サブメニューアイコンURLが404ページになっている部分を修正
vektor-inc/vektor-wp-libraries pull request #136
Opened 2024-07-24 06:58 UTC by mtdkei

https://github.com/vektor-inc/lightning/pull/1173
で修正箇所が異なっているようだったのでこちらに移動して修正しました。
また、gulp sass_vk-mobile-navで、gulp-sass パッケージがデフォルトの Sass コンパイラを持たなくなったためにエラーが発生したため、gulpfile.js 内で明示的に Sass コンパイラを設定しました。

2024-07-24 07:11 UTC, mtdkei commented
@kurudrive 
vk-mobile-navを書き換えてコンパイルし、出力されたCSSを各テーマにコピペするところまでは行ってみました。
あとは以下のcssも`background: url("../images/vk-menu-acc-icon-open-white.svg") center 50% `になっているので、vk-mobile-navと同じように修正したいのですがどうしたらいいでしょうか。
```
/app/public/wp-content/themes/lightning/_g2/assets/css/common.css
/app/public/wp-content/themes/lightning/_g3/assets/css/common.css
/app/public/wp-content/themes/katawara/assets/css/style.min.css
/app/public/wp-content/themes/lightning-pro/assets/css/common.css

```

2024-10-16 06:42 UTC, kurudrive requested changes

2024-10-16 06:42 UTC, kurudrive commented on vk-mobile-nav/package/_scss/vk-mobile-nav-dark.scss
>  		no-repeat;
@mtdkei ↓じゃなくて（・ｗ・？

```suggestion
	background: var(--vk-menu-acc-icon-open-white-bg-src) center 50% no-repeat;
```

2024-10-16 06:42 UTC, kurudrive commented on vk-mobile-nav/package/_scss/vk-mobile-nav-dark.scss
>  .vk-menu-acc .acc-btn-close {
@mtdkei ↓これもおなじ形式で変更しないといけないのでは（・ｗ・？

2024-10-17 00:52 UTC, mtdkei commented
@kurudrive 
ご確認ありがとうございます。ご指摘の点を含めて修正してみました。

2024-10-17 06:24 UTC, kurudrive commented
@mtdkei あーりがとうございまっする！

2024-10-17 06:25 UTC, kurudrive approved these changes

2024-10-17 06:25 UTC, merged